name: wrightyho
favicon: null
layout_spectrum: 0.4800047839526087
typography_spectrum: 0.41767720878124237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6062951360363513
  lightness: 0.5727372781839222
  saturation: 0.36950079747475684
  rhythmicContrast: 0.09070623200386763
purpose: []
